.PHONY: all clean

all: progA progB progC

progA: progA.c
	gcc -g -Wall -o progA progA.c

progB: progB.c
	gcc -g -Wall -o progB progB.c

progC: progC.c
	gcc -g -Wall -o progC progC.c

clean:
	rm -f progA
	rm -f progB
	rm -f progC