#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>
#include <stdlib.h>

/* run locally on 'server' called by a remote client. */

int ascending_comparator(const void *a, const void *b) {
  double c = * (double *) a;
  double d = * (double *) b;
  if(c > d) {
    return 1;
  } else if(c < d) {
    return -1;
  }
  return 0;
}

int descending_comparator(const void *a, const void *b) {
  double c = * (double *) a;
  double d = * (double *) b;
  if(c < d) {
    return 1;
  } else if(c > d) {
    return -1;
  }
  return 0;
}

/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */
input_data * average_1(input_data *input, CLIENT *client) 
  {
  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
    double *dp = input->input_data.input_data_val;
    int len = input->input_data.input_data_len;
    double doubles[(len)];
    int i;

    for(i = 0; i < len; i++){
      doubles[i] = *dp;
      dp++;
    }

    int comparator = (int) *dp;
    dp++;

    if(comparator == 1) {
      qsort(doubles, len, sizeof(double), ascending_comparator);
    } else if (comparator == -1){
      qsort(doubles, len, sizeof(double), descending_comparator);
    } else {
      qsort(doubles, len, sizeof(double), ascending_comparator);
    }

    dp = input->input_data.input_data_val;

    for(i = 0; i < len; i++) {
      *dp = doubles[i];
      dp++;
    }

    return (input);
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
input_data * average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }
